version: '3.8' # Versão mais recente, mas '3' também funciona
services:
  api:
    build: .
    ports:
      - "1313:1313"
    volumes:
      - .:/app # Monta o código local para desenvolvimento com hot-reload
    environment:
      - FLASK_ENV=development # Garante que o Flask rode em modo de desenvolvimento
      - FLASK_APP=app.py      # Bom para explicitar qual arquivo Flask deve rodar
      - JWT_SECRET_KEY=my_super_secret_compose_key # Exemplo de como passar via env
    # Se você quiser que o container use gunicorn como no Procfile:
    # command: ["gunicorn", "-b", "0.0.0.0:1313", "app:app"]
    # Mas para desenvolvimento com FLASK_ENV=development, o servidor do Flask é melhor.
